import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Header from '../components/Header'
import Pricing from '../components/Pricing'
import Services from '../components/Services'
import Testimonials from '../components/Testimonials'
import Footer from '../components/Footer'


export default function Home({list, symbol}) {
  console.log(symbol)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
       <Header/>
       <Pricing data={list.currencies} />
       <Services/>
       <Testimonials/>
       <Footer/>
      </main>
    </>
  )
}

export const getStaticProps=async()=>{
  try{
    const myHeaders = new Headers();
    myHeaders.append("apikey", "g8HhsPzdptDtov298Xz5Q3LBvIsvULYd");

    const requestOptions = {
      method: 'GET',
      redirect: 'follow',
      headers: myHeaders
    };

    const response = await fetch("https://api.apilayer.com/currency_data/list", requestOptions);
    const data = await response.json();
    
    return{
      props:{
         list:data
      }

    }

  }catch(error){
    console.log(error.message)
  }

 
}



